openapi: 3.0.0
info:
  title: Short Notes Service API
  version: 1.0.0
  description: API for managing short notes.
tags:
  - name: Notes
    description: "Get notes details"
  - name: Share Access
    description: "Get shared access details"
  - name: User Statistics
    description: "Get users statistics"

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          format: int
          readOnly: true
          title: Id
        title:
          type: string
          maxLength: 100
          minLength: 1
          title: Title
        content:
          type: string
          maxLength: 404
          minLength: 1
          title: Content
        categories:
          type: array
          items:
            type: string
          title: Categories
        updatedAt:
          type: string
          format: date-time
          readOnly: true
          title: UpdatedAt
    UserStatistics:
      type: object
      properties:
        user_notes:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              updatedAt:
                  type: string
                  format: date-time
                  readOnly: true
                  title: UpdatedAt
            required:
              - title
        user_shared_accesses:
          type: array
          items:
            type: object
            properties:
              title:
                  type: string
              last_edit:
                type: string
                format: date-time
    SharedNote:
      type: object
      properties:
        title:
          type: string
        updated_at:
          type: string
          format: date-time

paths:
  /notes:
    get:
      summary: Get all notes
      description: Retrieve all short notes for the authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: "1"
                title: "Example Note"
                content: "This is an example note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: "Forbidden"
      tags:
        - Notes

    post:
      summary: Create a new note
      description: Create a new short note for the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            example:
                id: "1"
                title: "New Note"
                content: "This is an new note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"
      responses:
        '201':
          description: Note created successfully
          content:
            application/json:
              example:
                id: "1"
                title: "New Note"
                content: "This is an new note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Bad Request"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"
      tags:
        - Notes

  /view_note/{noteId}:
    get:
      summary: Get a specific note
      description: Retrieve a specific short note by ID for the authenticated user.
      parameters:
        - name: noteId
          in: path
          required: true
          description: ID of the note
          schema:
            type: string
            format: int
      tags:
        - Notes

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: "2"
                title: "New Note"
                content: "This is an new note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Not Found"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"

  /edit_note/{noteId}:
    put:
      summary: Update a specific note
      description: Update the content or tags of a specific short note by ID for the authenticated user.
      parameters:
        - name: noteId
          in: path
          required: true
          description: ID of the note
          schema:
            type: string
            format: int

      requestBody:
        required: true
        content:
          application/json:
            example:
                id: "1"
                title: "New Note"
                content: "This is an new note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"


      responses:
        '200':
          description: Note updated successfully
          content:
            application/json:
              example:
                id: "1"
                title: "New Note"
                content: "This is an new note."
                categories: "test"
                createdAt: "2023-01-01T12:00:00Z"
                updatedAt: "2023-01-01T12:30:00Z"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Not Found"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"
      tags:
        - Notes
  /delete_note/{noteId}:
    delete:
      summary: Delete a specific note
      description: Delete a specific short note by ID for the authenticated user.
      parameters:
        - name: noteId
          in: path
          required: true
          description: ID of the note
          schema:
            type: string
            format: int

      responses:
        '204':
          description: Note deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Not Found"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"

      tags:
        - Notes

  /notes/{note_id}/share:
    post:
      summary: "Share note access"
      description: "Share access to a note with another user"
      parameters:
        - name: note_id
          in: path
          description: "ID of the note to share"
          required: true
          schema:
            type: integer
        - name: body
          in: query
          description: "ShareAccessForm data"
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: "Username of the user to share the note with"
      responses:
        200:
          description: "Note access shared successfully"
        400:
          description: "Bad Request - Maximum shared accesses reached or user already has access to the note"
        404:
          description: "Not Found - User with the given username doesn't exist"
      tags:
        - Share Access

  /shared_notes/:
    get:
      summary: "Get shared notes"
      description: "Retrieve notes shared with the authenticated user"
      responses:
        200:
          description: "List of shared notes"
          content:
            application/json:
              example:
                - title: "Shared Note 1"
                  id: "1"
                  updated_at: "2023-01-01T12:00:00Z"
                - title: "Shared Note 2"
                  id: "2"
                  updated_at: "2023-01-01T12:30:00Z"
                - title: "Shared Note 3"
                  id: "3"
                  updated_at: "2023-01-01T13:00:00Z"
        401:
          description: "Unauthorized - User not logged in"
      tags:
        - Share Access

  /statistics/:
    get:
      summary: "View user statistics"
      description: "Retrieve statistics for the authenticated user"
      responses:
        200:
          description: "User statistics retrieved successfully"
          content:
            application/json:
              example:
                    user_notes:
                      - id: "1"
                        title: "Example Note"
                        content: "This is an example note."
                        categories: "example"
                        updatedAt: "2023-01-01T12:30:00Z"
                    user_shared_accesses:
                      - note:
                          id: "2"
                          title: "Another Note"
                          content: "This is another note."
                          categories: "another"
                          updatedAt: "2023-01-01T12:40:00Z"
                        last_edit: "2023-01-01T13:00:00Z"
                      - note:
                          id: "3"
                          title: "Third Note"
                          content: "This is a third note."
                          categories: "third"
                          updatedAt: "2023-01-01T12:50:00Z"
        401:
          description: "Unauthorized - User not logged in"
      tags:
        - User Statistics
